on: [push]

name: CI

jobs:
  build_web_app:
    name: Web App
    runs-on: ubuntu-latest
    env:
      OIDC_ISSUER: https://nft-login.chriamue.net
      OIDC_CLIENT_ID: "0x420d2a6E87D87992EB01e5BFe762B3F437dBfD85"
      OIDC_REDIRECT_URI: https://nft-login.github.io/svelte-oidc/
      OIDC_POST_LOGOUT_REDIRECT_URI: https://nft-login.github.io/svelte-oidc/
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install node dependencies
        run: npm install
      - name: Build App
        run: PUBLIC_URL=/svelte-oidc npm run showcase:build && cp -R public gh-public

      - name: Build App for okt
        env:
          OIDC_ISSUER: https://okt-nft-login.chriamue.net
          OIDC_CLIENT_ID: "0x886B6781CD7dF75d8440Aba84216b2671AEFf9A4"
          OIDC_REDIRECT_URI: https://nft-login.github.io/svelte-oidc/okt/
          OIDC_POST_LOGOUT_REDIRECT_URI: https://nft-login.github.io/svelte-oidc/okt/
        run: PUBLIC_URL=/svelte-oidc/okt npm run showcase:build && cp -R public gh-public/okt

      - name: Deploy App
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./gh-public
          keep_files: true
